name: Trigger auto deployment for springcontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/springcontainer-AutoDeployTrigger-3722dbe2-4912-41ed-b608-06e868913c0b.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca3d182c5f95acr.azurecr.io
          registryUsername: ${{ secrets.SPRINGCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRINGCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: springcontainer
          resourceGroup: v-pravallika-mindtree
          imageToBuild: ca3d182c5f95acr.azurecr.io/springcontainer:${{ github.sha }}
          

     

